services:
  huntressgame:
    build: .
    container_name: huntressgame
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/assets
      # - ./data/game.db:/app/game.db
      # - ./static:/app/static
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
