services:
  huntressgame:
    build: .
    user: 1000:1000
    container_name: huntressgame
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/assets
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
