services:
  ctfgames:
    build: .
    user: 1000:1000
    container_name: ctfgames
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock # for docker challenges
    environment:
      - FLASK_ENV=production
      - DOCKER_URL=localhost
    restart: unless-stopped
