services:
  ctfgames:
    build: .
    container_name: ctfgames
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock # for docker challenges
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=a5d5d08e5e3c637c8c370527233f291d
    restart: unless-stopped

  adminer:
    build:
      context: .
      dockerfile: Dockerfile_adminer
    volumes:
      - ./data/game.db:/game.db
    environment:
      ADMINER_DEFAULT_DB: /game.db
    restart: unless-stopped

  caddy:
    image: caddy:latest
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - adminer
