services:
  optgames:
    build: .
    container_name: optgames_ctf
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock # for docker challenges
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=a5d5d08e5e3c637c8c370527233f291d
    restart: unless-stopped

  dbbrowser:
    container_name: optgames_dbbrowser
    image: linuxserver/sqlitebrowser:latest
    volumes:
      - ./data/game.db:/config/game.db
    restart: unless-stopped

  caddy:
    container_name: optgames_caddy
    image: caddy:latest
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - dbbrowser
